version: '3'

networks:
  www-calendar:

services:
  app:
    container_name: main
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./source:/app
      - ./.env:/app/.env
    ports:
      - ${PORT}:5000
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      www-calendar:
    depends_on:
      - mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_HOST=${MYSQL_HOST}
      - PMA_PORT=${MYSQL_PORT}
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    networks:
      www-calendar:

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      www-calendar:
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always

volumes:
  mysqldata:
